service: crud-api

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.tableName}

custom:
  tableName: Worker

plugins:
  - serverless-iam-roles-per-function

functions: 
  getAllWorker:
    handler: api.getAllWorker
    name: get-all-worker
    events:
      - http:
          path: workers
          method: GET
  getWorker:
    handler: api.getWorker
    name: get-worker
    events:
      - http:
          path: worker/{workerId}
          method: GET
    
  createWorker:
    handler: api.createWorker
    name: create-worker
    events:
      - http:
          path: worker
          method: POST
  updateWorker:
    handler: api.updateWorker
    name: update-worker
    events:
      - http:
          path: worker/{workerId}
          method: PUT 
  deleteWorker:
    handler: api.deleteWorker
    name: delete-worker
    events:
      - http:
          path: worker/{workerId}
          method: DELETE

resources:
  Resources:
    Worker:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
            ## make the primary key